<script lang="ts">
	import { onMount } from 'svelte';
	let pageTitle = 'Cookies - Software Engineering Network';
	onMount(() => {
		document.title = pageTitle;
	});
</script>

<h1 class="mt-14 regular-font text-black uppercase dark:text-white">Cookies</h1>

<h2 class="mt-14 regular-font text-black uppercase dark:text-white">What are Cookies?</h2>
<p class="mt-6 text-lg regular-font text-black dark:text-gray">
	We at Software Engineering Network use cookies in order to make the website function as good as
	possible. A Cookie is a small text file that is stored in the visitor’s browser and is used in
	order to improve the functionalities of the website, but also to give you the best service
	possible.
	<br /><br />
	There are two types of cookies which are the following:
</p>
<ul class="list-disc list-inside mt-4 regular-font text-black dark:text-gray">
	<li>
		<strong>Persistent cookies</strong> – stays in the visitor’s computer under a determined period.
	</li>
	<li>
		<strong>Session cookies</strong> – are stored temporary in the computer’s memory during the visit
		of a website. These cookies will be erased when a visitor is closing the browser.
	</li>
</ul>

<h2 class="mt-14 regular-font text-black uppercase dark:text-white">
	Software Engineering Network's use of Cookies
</h2>
<p class="mt-6 text-lg regular-font text-black dark:text-gray">
	In this website Vercel is used in order to both track and report the website’s traffic. The
	purpose of Software Engineering Network’s use of Vercel Analytics is to analyze cookies that are
	generated by you as a visitor. Only visitor statistics are analyzed in an overall level, which
	cannot identify you as a person.
</p>

<h2 class="mt-14 regular-font text-black uppercase dark:text-white">
	Do you want to remove or block Cookies?
</h2>
<p class="mt-6 text-lg regular-font text-black dark:text-gray">
	As a visitor you can remove cookies that are already stored or block the use of cookies by using
	the settings of your browser. Information on how to proceed can usually be found in the browser’s
	help-menu. It is important that you should know that cookies can be stored automatically by most
	browsers and that specific functionalities can cease or cannot function fully if cookies are
	removed or blocked.
	<br /><br />
	If you want to read more information about cookies you can visit the Swedish Post and Telecom Authority
	who monitors the electronic communications and postal sectors in Sweden.
	<br /><br />
	If you want to learn more about Software Engineering Network’s treatment of personal data, you can
	read our Privacy Policy.
</p>
